name: 📊 PCM Stats Change Request
description: Request a new change to cyclist statistics
title: "[STATS CHANGE] "
labels: ["change-request", "automated"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📊 PCM Stats Change Request
        
        Fill out this form to create a new stats change request.
        Required fields: Title, Race URL
        The date will be automatically set based on when the issue is created.
        ----

  - type: input
    id: race_url
    attributes:
      label: Race URL
      description: FirstCycling.com race URL to extract cyclist data from
      placeholder: "https://firstcycling.com/race.php?r=XXXXX"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the change
      placeholder: "Update stats after Tour de France Stage 1..."
    validations:
      required: false

  - type: dropdown
    id: namespace
    attributes:
      label: Namespace
      description: Which namespace should this change be applied to?
      options:
        - 2025dev
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Confirmation
      description: Please confirm the following
      options:
        - label: I have verified the race URL is correct and accessible
          required: true
        - label: I understand this will create an automated pull request
          required: true
