name: Automated Change Request Processing

on:
  issues:
    types: [opened]

jobs:
  process-stats-change-request:
    if: startsWith(github.event.issue.title, '[STATS CHANGE]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Process change request and create branch
        id: process-change
        run: |
          # Configure git
          echo "🔧 Configuring git..."
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Process automated change request (this also parses the form data)
          echo "⚙️ Processing automated change request..."
          python src/pcm_cli.py process-automated-change "${{ github.event.issue.body }}" --github-actor "${{ github.actor }}" --issue-title "${{ github.event.issue.title }}"
          
          # Get values from the output file
          BRANCH_NAME=$(grep "branch_name=" $GITHUB_OUTPUT | cut -d'=' -f2)
          CHANGE_NAME=$(grep "change_name=" $GITHUB_OUTPUT | cut -d'=' -f2)
          AUTHOR=$(grep "author=" $GITHUB_OUTPUT | cut -d'=' -f2)
          DATE=$(grep "date=" $GITHUB_OUTPUT | cut -d'=' -f2)
          NAMESPACE=$(grep "namespace=" $GITHUB_OUTPUT | cut -d'=' -f2)
          RACE_URL=$(grep "race_url=" $GITHUB_OUTPUT | cut -d'=' -f2)
          CYCLISTS_FOUND=$(grep "cyclists_found=" $GITHUB_OUTPUT | tail -1 | cut -d'=' -f2)
          SUCCESS=$(grep "success=" $GITHUB_OUTPUT | tail -1 | cut -d'=' -f2)
          
          # Create and checkout branch
          echo "🌿 Creating branch: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          
          # Check if processing was successful
          if [ "$SUCCESS" = "true" ]; then
            echo "✅ Processing successful, committing changes..."
            
            # Add and commit changes
            git add .
            git commit -m "Add change: $CHANGE_NAME

          - Author: $AUTHOR
          - Date: $DATE
          - Namespace: $NAMESPACE
          - Race URL: $RACE_URL
          - Cyclists found: $CYCLISTS_FOUND

          Generated from issue #${{ github.event.issue.number }}"
            
            echo "📤 Pushing branch to origin..."
            git push origin "$BRANCH_NAME"
          else
            echo "❌ Processing failed, not committing changes"
            exit 1
          fi

      - name: Push branch
        if: steps.process-change.outputs.success == 'true'
        run: |
          echo "Branch push was handled in the previous step"

      - name: Create Pull Request
        if: steps.process-change.outputs.success == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.process-change.outputs.branch_name }}
          title: "Change: ${{ steps.process-change.outputs.change_name }}"
          body: |
            ## 📊 Automated Change Request
            
            **Created from Issue:** #${{ github.event.issue.number }}
            
            ### Details
            - **Change Name:** ${{ steps.process-change.outputs.change_name }}
            - **Date:** ${{ steps.process-change.outputs.date }}
            - **Author:** ${{ steps.process-change.outputs.author }}
            - **Namespace:** ${{ steps.process-change.outputs.namespace }}
            - **Race URL:** ${{ steps.process-change.outputs.race_url }}
            
            ### Description
            ${{ steps.process-change.outputs.description }}
            
            ### Generated Content
            - **Cyclists Found:** ${{ steps.process-change.outputs.cyclists_found }}
            - **Files Created:** 
              - `${{ steps.process-change.outputs.change_file_path }}`
              - SQL files generated by process-changes command
            
            ### Next Steps
            1. Review the generated change.yaml file
            2. Verify cyclist data is correct
            3. Update any missing or incorrect stats
            4. Approve and merge when ready
            
            ---
            
            🤖 *This PR was automatically generated by GitHub Actions*
          labels: |
            automated-change
            needs-review

      - name: Comment on issue success
        if: steps.process-change.outputs.success == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ✅ Change Request Processed Successfully!
            
            Your change request has been processed and a pull request has been created.
            
            ### Results
            - **Branch Created:** `${{ steps.process-change.outputs.branch_name }}`
            - **Cyclists Found:** ${{ steps.process-change.outputs.cyclists_found }}
            - **Pull Request:** Created automatically
            
            ### What's Next?
            1. Check the generated pull request
            2. Review the cyclist data in the change.yaml file
            3. Make any necessary adjustments
            4. Request review when ready
            
            Thank you for contributing! 🚴‍♂️

      - name: Comment on issue failure
        if: steps.process-change.outputs.success == 'false'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## ❌ Change Request Processing Failed
            
            There was an error processing your change request:
            
            **Error:** ${{ steps.process-change.outputs.error || 'Unknown error occurred' }}
            
            Please check the details and try again, or contact a maintainer for assistance.

      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            This issue has been automatically processed and closed. 
            ${{ steps.process-change.outputs.success == 'true' && 'The change request is now available as a pull request for review.' || 'Please check the error message above and try again if needed.' }}
