name: cicd

on:
  pull_request:
    branches: [ "main", "uat", "change/*" ]  # Allow PRs to protected branches

jobs:
  # Test job that runs on all branches first
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  detect_branch_type:
    runs-on: ubuntu-latest
    needs: validate  # Only run after tests pass
    outputs:
      branch_type: ${{ steps.detect.outputs.branch_type }}
    steps:
    - name: Detect branch type
      id: detect
      run: |
        if [[ "${{ github.head_ref || github.ref_name }}" == "change/"* ]]; then
          echo "branch_type=change" >> $GITHUB_OUTPUT
        else
          echo "branch_type=other" >> $GITHUB_OUTPUT
        fi

  change_branch:
    runs-on: ubuntu-latest
    needs: [validate, detect_branch_type]  # Require both tests and branch detection
    if: ${{ needs.detect_branch_type.outputs.branch_type == 'change' }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history
    - name: Checkout current branch
      run: |
        git checkout ${{ github.head_ref || github.ref_name }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Validate YAML files
      run: |
        python src/pcm_cli.py validate-yaml
    - name: Process all namespaces
      run: |
        python src/pcm_cli.py process-changes
    - name: Commit and push generated files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-generated: Process changes and update stats files
          
          - Generated inserts.sql files for new changes
          - Updated stats.yaml files with new cyclist data
          
          Generated by: ${{ github.workflow }} #${{ github.run_number }}"
          git push origin ${{ github.head_ref || github.ref_name }}
        fi

  uat_branch:
    runs-on: ubuntu-latest
    needs: validate  # Only run after validate passes
    if: ${{ github.ref == 'refs/heads/uat' }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history
    - name: Checkout current branch
      run: |
        git checkout ${{ github.head_ref || github.ref_name }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: UAT branch processing (if needed)
      run: |
        echo "UAT branch detected - processing changes for UAT environment"
        
  main_branch:
    runs-on: ubuntu-latest
    needs: validate  # Only run after validate passes
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Fetch full history
    - name: Checkout current branch
      run: |
        git checkout ${{ github.head_ref || github.ref_name }}
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Main branch processing (if needed)
      run: |
        echo "Main branch detected - processing changes for production environment"